export const SITE_CONFIG = {
  title: "THE TEACHER EFFECT",
  institute: "IIT PATNA",
  batchName: "Online Certification Batch",
  occasion: "TEACHERS' DAY",
  date: "September 5",
  songTitle: "Aap Se Hi Seekha",
  songTagline: "Created with AI. Felt by humans.",
  audioSrc: "/audio/aap-se-hi-seekha.mp3",
  teacherModeCode: "MASAI",
  credit: "MADE BY YASH",
  stats: [
    { value: "\u221E", label: "Questions Answered" },
    { value: "\u221E", label: "Lessons Taught" },
    { value: "\u221E", label: "Ideas Sparked" },
    { value: "100%", label: "Gratitude" },
  ],
  bookPages: [
    {
      title: "Page One",
      body: "Every class began the same way \u2014 a login, a login sound, and a quiet hope that today's lesson would make sense.",
    },
    {
      title: "Page Two",
      body: "Screens replaced classrooms. Chat boxes replaced raised hands. But the teaching never lost its warmth.",
    },
    {
      title: "Page Three",
      body: "Behind every muted mic was a student trying to understand. Behind every shared screen was a teacher trying to be understood.",
    },
    {
      title: "Page Four",
      body: "Doubts were typed in silence and answered with patience. Distance never stood a chance against dedication.",
    },
    {
      title: "Page Five",
      body: "We learned to read expressions through pixels, and care through cadence of voice.",
    },
    {
      title: "Page Six",
      body: "Every 'can you repeat that' was met without complaint. Every late-night doubt session was still a class.",
    },
    {
      title: "Page Seven",
      body: "And somewhere between the buffering and the breakthroughs, we realised \u2014 we had been taught, truly, all along.",
    },
  ],
  capWords: ["KNOWLEDGE", "GROWTH", "FUTURE"],
  classroomModes: [
    { id: "morning", label: "Morning" },
    { id: "day", label: "Day" },
    { id: "evening", label: "Evening" },
    { id: "celebration", label: "Celebration" },
  ] as const,
  terminalLines: [
    "[boot] starting gratitude.kernel",
    "[scan] indexing four semesters of lessons",
    "[trace] resolving every doubt -> every answer",
    "[sync] 72 student nodes connected",
    "[write] compiling final teacher tribute",
    "[status] READY // gratitude online",
  ],
  navItems: [
    { id: "home", label: "Home" },
    { id: "song", label: "Song" },
    { id: "experience", label: "Experience" },
    { id: "lessons", label: "Lessons" },
    { id: "tribute", label: "Tribute" },
    { id: "next", label: "Next" },
  ] as const,
  puzzleWord: "THANKYOU",
  lyrics: [
    {
      section: "Intro",
      lines: [
        "Ek screen ke us paar se,",
        "Aai ek roshni hum tak...",
        "Na samne mile, na hath mila,",
        "Phir bhi dil tak pahunchi har baat...",
      ],
    },
    {
      section: "Verse 1",
      lines: [
        "Jab code ki duniya anjani thi,",
        "Har line humein kuch kah jati thi,",
        "Kab bracket tha, kab error aaya,",
        "Aapne har mushkil ko samjhaya.",
        "",
        "Kabhi Python ki woh chhoti si line,",
        "Kabhi logic ko karna tha define,",
        "Jo sawal humein rok dete the,",
        "Aap jawab se aage le jate the.",
      ],
    },
    {
      section: "Pre-Chorus",
      lines: [
        "Humein sirf code nahi sikha,",
        "Humein sochna bhi aapse sikha,",
        "Har galti ko mauka mana,",
        "Har mushkil se ladna jana.",
      ],
    },
    {
      section: "Chorus",
      lines: [
        "Shukriya, teacher, shukriya,",
        "Aapne hi rasta dikha diya,",
        "Shukriya, teacher, shukriya,",
        "Aapne hi hausla jaga diya.",
        "",
        "Jab screen ke us paar tha andhera,",
        "Aapne diya tha seedha sa phera,",
        "Ek baat aapki, ek dant bhi sahi,",
        "Dil mein ab tak wahi rah gayi.",
        "",
        "Shukriya, teacher, shukriya,",
        "Aapne hi kal ko naam diya,",
        "Shukriya, teacher, shukriya,",
        "Aapne hi humein hum sa diya.",
      ],
    },
    {
      section: "Verse 2",
      lines: [
        "Kabhi class mein chehra samne nahi,",
        "Phir bhi apnapan tha kahin na kahin,",
        "Aawaz mein tha ek bharosa sa,",
        "\"Kar loge tum\" \u2014 bas itna kafi tha.",
        "",
        "Jab program bar bar fail hua,",
        "Jab logic kahin jaake ruk gaya,",
        "Aapne kaha, \"Phir se koshish karo,\"",
        "Aur humne sikha \u2014 kabhi mat daro.",
      ],
    },
    {
      section: "Pre-Chorus",
      lines: [
        "Har error ek seekh bana,",
        "Har failure ek rasta bana,",
        "Jo kal tak mushkil lagta tha,",
        "Aaj wahi apna lagta hai.",
      ],
    },
    {
      section: "Chorus",
      lines: [
        "Shukriya, teacher, shukriya,",
        "Aapne hi rasta dikha diya,",
        "Shukriya, teacher, shukriya,",
        "Aapne hi hausla jaga diya.",
        "",
        "Jab screen ke us paar tha andhera,",
        "Aapne diya tha seedha sa phera,",
        "Ek baat aapki, ek dant bhi sahi,",
        "Dil mein ab tak wahi rah gayi.",
        "",
        "Shukriya, teacher, shukriya,",
        "Aapne hi kal ko naam diya,",
        "Shukriya, teacher, shukriya,",
        "Aapne hi humein hum sa diya.",
      ],
    },
    {
      section: "Bridge",
      lines: [
        "Kuch teachers kitab padhate hain,",
        "Kuch zindagi samjhate hain,",
        "Kuch sirf ek sawal ka jawab,",
        "Aur andar ke dar mitate hain.",
        "",
        "Kuch samne hote hain,",
        "Kuch screen ke peeche,",
        "Par unki mehnat pahunchti hai,",
        "Hum sab ke kal ke neeche.",
        "",
        "Aaj hum jo seekh rahe hain,",
        "Kal duniya ko batayenge,",
        "Aapne jo beej boya hai,",
        "Use ek din ped banayenge.",
      ],
    },
    {
      section: "Final Chorus",
      lines: [
        "Shukriya, mere teachers,",
        "Aapne andheron ko cheer diya,",
        "Har bar jab hum gire,",
        "Aapne phir se khada kiya.",
        "",
        "Aapki ek baat, ek nazar,",
        "Aaj bhi saath chalti hai,",
        "Jis raah se hum guzar rahe hain,",
        "Wo aapki mehnat lagti hai.",
        "",
        "Shukriya, un sab teachers ko,",
        "Jo hum par yakeen karte hain,",
        "Hum gir bhi jayein kitni bar,",
        "Phir uthna humein sikhate hain.",
        "",
        "Aaj Teachers Day ke is din,",
        "Bas itna kahna hai dil se...",
        "",
        "Aap sirf humein padhate nahi,",
        "Aap hamara kal banate hain.",
      ],
    },
    {
      section: "Outro",
      lines: [
        "Ek screen ke us paar se,",
        "Jo roshni hum tak aai...",
        "",
        "Wo sirf ek class nahi thi,",
        "Wo nayi si pehchan thi.",
        "",
        "Shukriya...",
        "Har teacher ka.",
        "",
        "Shukriya...",
        "Har seekh ka.",
        "",
        "Aur shukriya...",
        "Humein hum banane ke liye.",
      ],
    },
  ],
} as const

export type ClassroomMode = (typeof SITE_CONFIG.classroomModes)[number]["id"]
